name: ProAssistant Build

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11', '17']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Run Check
        run: mvn checkstyle:check