name: ProAssistant Build

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['19']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java-version }}

      - name: Run Tests
        run: mvn test

#      - name: Run Check
#        run: mvn checkstyle:check

      - name: Build with Maven
        run: mvn clean package